package com.eps.mybatis.auto.entity;

public class AnalyPersonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_person.USER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_person.TEST_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_person.SUBJECT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer subjectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_person.USER_ID
     *
     * @return the value of e_analy_person.USER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_person.USER_ID
     *
     * @param userId the value for e_analy_person.USER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_person.TEST_ID
     *
     * @return the value of e_analy_person.TEST_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_person.TEST_ID
     *
     * @param testId the value for e_analy_person.TEST_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_person.SUBJECT_ID
     *
     * @return the value of e_analy_person.SUBJECT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_person.SUBJECT_ID
     *
     * @param subjectId the value for e_analy_person.SUBJECT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
}