package com.eps.mybatis.auto.entity;

import java.util.Date;

public class AnalyClass extends AnalyClassKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.GRADE_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.SCHOOL_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.TEACHER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.STUDENT_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer studentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.SEX_RATIO
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String sexRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.JOIN_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer joinNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.SCORE_AVG
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Double scoreAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.SCORE_AVG_G
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Double scoreAvgG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.SCORE_MAX
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Double scoreMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.SCORE_MIN
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Double scoreMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.SCORE_AVG_GR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer scoreAvgGr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.STANDARD_S
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer standardS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.STANDARD_D
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer standardD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.TOTAL
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.TOP_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer topNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.IMPROVE_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer improveNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.FALL_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer fallNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.STABLE_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer stableNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.HIGH_AVG
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Double highAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.LOW_AVG
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Double lowAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.HIGH_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Double highNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.LOW_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Double lowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.EXCELLENT
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer excellent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.GOOD
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer good;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.PASS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.WEEK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.TERRIBLE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer terrible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_analy_class.TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.GRADE_ID
     *
     * @return the value of e_analy_class.GRADE_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.GRADE_ID
     *
     * @param gradeId the value for e_analy_class.GRADE_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.SCHOOL_ID
     *
     * @return the value of e_analy_class.SCHOOL_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.SCHOOL_ID
     *
     * @param schoolId the value for e_analy_class.SCHOOL_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.TEACHER_ID
     *
     * @return the value of e_analy_class.TEACHER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.TEACHER_ID
     *
     * @param teacherId the value for e_analy_class.TEACHER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.STUDENT_NUM
     *
     * @return the value of e_analy_class.STUDENT_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.STUDENT_NUM
     *
     * @param studentNum the value for e_analy_class.STUDENT_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setStudentNum(Integer studentNum) {
        this.studentNum = studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.SEX_RATIO
     *
     * @return the value of e_analy_class.SEX_RATIO
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getSexRatio() {
        return sexRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.SEX_RATIO
     *
     * @param sexRatio the value for e_analy_class.SEX_RATIO
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setSexRatio(String sexRatio) {
        this.sexRatio = sexRatio == null ? null : sexRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.JOIN_NUM
     *
     * @return the value of e_analy_class.JOIN_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getJoinNum() {
        return joinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.JOIN_NUM
     *
     * @param joinNum the value for e_analy_class.JOIN_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setJoinNum(Integer joinNum) {
        this.joinNum = joinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.SCORE_AVG
     *
     * @return the value of e_analy_class.SCORE_AVG
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Double getScoreAvg() {
        return scoreAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.SCORE_AVG
     *
     * @param scoreAvg the value for e_analy_class.SCORE_AVG
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setScoreAvg(Double scoreAvg) {
        this.scoreAvg = scoreAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.SCORE_AVG_G
     *
     * @return the value of e_analy_class.SCORE_AVG_G
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Double getScoreAvgG() {
        return scoreAvgG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.SCORE_AVG_G
     *
     * @param scoreAvgG the value for e_analy_class.SCORE_AVG_G
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setScoreAvgG(Double scoreAvgG) {
        this.scoreAvgG = scoreAvgG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.SCORE_MAX
     *
     * @return the value of e_analy_class.SCORE_MAX
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Double getScoreMax() {
        return scoreMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.SCORE_MAX
     *
     * @param scoreMax the value for e_analy_class.SCORE_MAX
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setScoreMax(Double scoreMax) {
        this.scoreMax = scoreMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.SCORE_MIN
     *
     * @return the value of e_analy_class.SCORE_MIN
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Double getScoreMin() {
        return scoreMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.SCORE_MIN
     *
     * @param scoreMin the value for e_analy_class.SCORE_MIN
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setScoreMin(Double scoreMin) {
        this.scoreMin = scoreMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.SCORE_AVG_GR
     *
     * @return the value of e_analy_class.SCORE_AVG_GR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getScoreAvgGr() {
        return scoreAvgGr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.SCORE_AVG_GR
     *
     * @param scoreAvgGr the value for e_analy_class.SCORE_AVG_GR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setScoreAvgGr(Integer scoreAvgGr) {
        this.scoreAvgGr = scoreAvgGr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.STANDARD_S
     *
     * @return the value of e_analy_class.STANDARD_S
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getStandardS() {
        return standardS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.STANDARD_S
     *
     * @param standardS the value for e_analy_class.STANDARD_S
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setStandardS(Integer standardS) {
        this.standardS = standardS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.STANDARD_D
     *
     * @return the value of e_analy_class.STANDARD_D
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getStandardD() {
        return standardD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.STANDARD_D
     *
     * @param standardD the value for e_analy_class.STANDARD_D
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setStandardD(Integer standardD) {
        this.standardD = standardD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.TOTAL
     *
     * @return the value of e_analy_class.TOTAL
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.TOTAL
     *
     * @param total the value for e_analy_class.TOTAL
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.TOP_NUM
     *
     * @return the value of e_analy_class.TOP_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getTopNum() {
        return topNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.TOP_NUM
     *
     * @param topNum the value for e_analy_class.TOP_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTopNum(Integer topNum) {
        this.topNum = topNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.IMPROVE_NUM
     *
     * @return the value of e_analy_class.IMPROVE_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getImproveNum() {
        return improveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.IMPROVE_NUM
     *
     * @param improveNum the value for e_analy_class.IMPROVE_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setImproveNum(Integer improveNum) {
        this.improveNum = improveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.FALL_NUM
     *
     * @return the value of e_analy_class.FALL_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getFallNum() {
        return fallNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.FALL_NUM
     *
     * @param fallNum the value for e_analy_class.FALL_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setFallNum(Integer fallNum) {
        this.fallNum = fallNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.STABLE_NUM
     *
     * @return the value of e_analy_class.STABLE_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getStableNum() {
        return stableNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.STABLE_NUM
     *
     * @param stableNum the value for e_analy_class.STABLE_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setStableNum(Integer stableNum) {
        this.stableNum = stableNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.HIGH_AVG
     *
     * @return the value of e_analy_class.HIGH_AVG
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Double getHighAvg() {
        return highAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.HIGH_AVG
     *
     * @param highAvg the value for e_analy_class.HIGH_AVG
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setHighAvg(Double highAvg) {
        this.highAvg = highAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.LOW_AVG
     *
     * @return the value of e_analy_class.LOW_AVG
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Double getLowAvg() {
        return lowAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.LOW_AVG
     *
     * @param lowAvg the value for e_analy_class.LOW_AVG
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setLowAvg(Double lowAvg) {
        this.lowAvg = lowAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.HIGH_NUM
     *
     * @return the value of e_analy_class.HIGH_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Double getHighNum() {
        return highNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.HIGH_NUM
     *
     * @param highNum the value for e_analy_class.HIGH_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setHighNum(Double highNum) {
        this.highNum = highNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.LOW_NUM
     *
     * @return the value of e_analy_class.LOW_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Double getLowNum() {
        return lowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.LOW_NUM
     *
     * @param lowNum the value for e_analy_class.LOW_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setLowNum(Double lowNum) {
        this.lowNum = lowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.EXCELLENT
     *
     * @return the value of e_analy_class.EXCELLENT
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getExcellent() {
        return excellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.EXCELLENT
     *
     * @param excellent the value for e_analy_class.EXCELLENT
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setExcellent(Integer excellent) {
        this.excellent = excellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.GOOD
     *
     * @return the value of e_analy_class.GOOD
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getGood() {
        return good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.GOOD
     *
     * @param good the value for e_analy_class.GOOD
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setGood(Integer good) {
        this.good = good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.PASS
     *
     * @return the value of e_analy_class.PASS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.PASS
     *
     * @param pass the value for e_analy_class.PASS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setPass(Integer pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.WEEK
     *
     * @return the value of e_analy_class.WEEK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.WEEK
     *
     * @param week the value for e_analy_class.WEEK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.TERRIBLE
     *
     * @return the value of e_analy_class.TERRIBLE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getTerrible() {
        return terrible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.TERRIBLE
     *
     * @param terrible the value for e_analy_class.TERRIBLE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTerrible(Integer terrible) {
        this.terrible = terrible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_analy_class.TIME
     *
     * @return the value of e_analy_class.TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_analy_class.TIME
     *
     * @param time the value for e_analy_class.TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }
}