package com.eps.mybatis.auto.entity;

import java.util.Date;

public class Arrange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.ARRANGE_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer arrangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.DATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.TEACHER_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.CLASS_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.TEST_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.SUBJECT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.GRADE_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.NETWORK_ADDR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String networkAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.NETWORK_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer networkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.USER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.ENDDATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_arrange.COST_TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer costTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.ARRANGE_ID
     *
     * @return the value of e_arrange.ARRANGE_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getArrangeId() {
        return arrangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.ARRANGE_ID
     *
     * @param arrangeId the value for e_arrange.ARRANGE_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setArrangeId(Integer arrangeId) {
        this.arrangeId = arrangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.DATE
     *
     * @return the value of e_arrange.DATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.DATE
     *
     * @param date the value for e_arrange.DATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.TEACHER_NAME
     *
     * @return the value of e_arrange.TEACHER_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.TEACHER_NAME
     *
     * @param teacherName the value for e_arrange.TEACHER_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.CLASS_ID
     *
     * @return the value of e_arrange.CLASS_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.CLASS_ID
     *
     * @param classId the value for e_arrange.CLASS_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.TEST_ID
     *
     * @return the value of e_arrange.TEST_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.TEST_ID
     *
     * @param testId the value for e_arrange.TEST_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.SUBJECT_ID
     *
     * @return the value of e_arrange.SUBJECT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.SUBJECT_ID
     *
     * @param subjectId the value for e_arrange.SUBJECT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.GRADE_ID
     *
     * @return the value of e_arrange.GRADE_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.GRADE_ID
     *
     * @param gradeId the value for e_arrange.GRADE_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.NETWORK_ADDR
     *
     * @return the value of e_arrange.NETWORK_ADDR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getNetworkAddr() {
        return networkAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.NETWORK_ADDR
     *
     * @param networkAddr the value for e_arrange.NETWORK_ADDR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setNetworkAddr(String networkAddr) {
        this.networkAddr = networkAddr == null ? null : networkAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.NETWORK_STATUS
     *
     * @return the value of e_arrange.NETWORK_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getNetworkStatus() {
        return networkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.NETWORK_STATUS
     *
     * @param networkStatus the value for e_arrange.NETWORK_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setNetworkStatus(Integer networkStatus) {
        this.networkStatus = networkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.USER_ID
     *
     * @return the value of e_arrange.USER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.USER_ID
     *
     * @param userId the value for e_arrange.USER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.ENDDATE
     *
     * @return the value of e_arrange.ENDDATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.ENDDATE
     *
     * @param enddate the value for e_arrange.ENDDATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_arrange.COST_TIME
     *
     * @return the value of e_arrange.COST_TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getCostTime() {
        return costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_arrange.COST_TIME
     *
     * @param costTime the value for e_arrange.COST_TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setCostTime(Integer costTime) {
        this.costTime = costTime;
    }
}