package com.eps.mybatis.auto.entity;

public class Catalog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_catalog.CA_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer caId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_catalog.SUBJECT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_catalog.CA_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String caName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_catalog.P_CA_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer pCaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_catalog.FREQUENCY
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_catalog.SORT_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_catalog.IN_USE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer inUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_catalog.REMARK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_catalog.CA_ID
     *
     * @return the value of e_catalog.CA_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getCaId() {
        return caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_catalog.CA_ID
     *
     * @param caId the value for e_catalog.CA_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setCaId(Integer caId) {
        this.caId = caId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_catalog.SUBJECT_ID
     *
     * @return the value of e_catalog.SUBJECT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_catalog.SUBJECT_ID
     *
     * @param subjectId the value for e_catalog.SUBJECT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_catalog.CA_NAME
     *
     * @return the value of e_catalog.CA_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getCaName() {
        return caName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_catalog.CA_NAME
     *
     * @param caName the value for e_catalog.CA_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setCaName(String caName) {
        this.caName = caName == null ? null : caName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_catalog.P_CA_ID
     *
     * @return the value of e_catalog.P_CA_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getpCaId() {
        return pCaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_catalog.P_CA_ID
     *
     * @param pCaId the value for e_catalog.P_CA_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setpCaId(Integer pCaId) {
        this.pCaId = pCaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_catalog.FREQUENCY
     *
     * @return the value of e_catalog.FREQUENCY
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_catalog.FREQUENCY
     *
     * @param frequency the value for e_catalog.FREQUENCY
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_catalog.SORT_NUM
     *
     * @return the value of e_catalog.SORT_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_catalog.SORT_NUM
     *
     * @param sortNum the value for e_catalog.SORT_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setSortNum(String sortNum) {
        this.sortNum = sortNum == null ? null : sortNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_catalog.IN_USE
     *
     * @return the value of e_catalog.IN_USE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getInUse() {
        return inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_catalog.IN_USE
     *
     * @param inUse the value for e_catalog.IN_USE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setInUse(Integer inUse) {
        this.inUse = inUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_catalog.REMARK
     *
     * @return the value of e_catalog.REMARK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_catalog.REMARK
     *
     * @param remark the value for e_catalog.REMARK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}