package com.eps.mybatis.auto.entity;

public class ExamQuestionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_question.EXAM_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam_question.QUES_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer quesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_question.EXAM_ID
     *
     * @return the value of e_exam_question.EXAM_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_question.EXAM_ID
     *
     * @param examId the value for e_exam_question.EXAM_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam_question.QUES_ID
     *
     * @return the value of e_exam_question.QUES_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getQuesId() {
        return quesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam_question.QUES_ID
     *
     * @param quesId the value for e_exam_question.QUES_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setQuesId(Integer quesId) {
        this.quesId = quesId;
    }
}