package com.eps.mybatis.auto.entity;

import java.util.Date;

public class Exam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.EXAM_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.EXAM_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String examName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.YEAR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.SEMESTER
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer semester;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.SUBJECT_NO
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String subjectNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.EXAM_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer examType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.B_TOPIC_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer bTopicNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.M_TOPIC_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer mTopicNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.TOTAL
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.CAREAOR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String careaor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.COST_TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer costTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.REMARK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.Q_RANDOM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer qRandom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.O_RANDOM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer oRandom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.B_CODE_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer bCodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.S_CODE_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer sCodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.O_CODE_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer oCodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.PASS_SCORE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Double passScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.EXAM_AREA
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer examArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.TEST_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.RELEASE_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer releaseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.RELEASE_TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.E_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer eStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_exam.GRADE_LEVEL
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer gradeLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.EXAM_ID
     *
     * @return the value of e_exam.EXAM_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.EXAM_ID
     *
     * @param examId the value for e_exam.EXAM_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.EXAM_NAME
     *
     * @return the value of e_exam.EXAM_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.EXAM_NAME
     *
     * @param examName the value for e_exam.EXAM_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setExamName(String examName) {
        this.examName = examName == null ? null : examName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.YEAR
     *
     * @return the value of e_exam.YEAR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.YEAR
     *
     * @param year the value for e_exam.YEAR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.SEMESTER
     *
     * @return the value of e_exam.SEMESTER
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getSemester() {
        return semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.SEMESTER
     *
     * @param semester the value for e_exam.SEMESTER
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setSemester(Integer semester) {
        this.semester = semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.SUBJECT_NO
     *
     * @return the value of e_exam.SUBJECT_NO
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getSubjectNo() {
        return subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.SUBJECT_NO
     *
     * @param subjectNo the value for e_exam.SUBJECT_NO
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setSubjectNo(String subjectNo) {
        this.subjectNo = subjectNo == null ? null : subjectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.EXAM_TYPE
     *
     * @return the value of e_exam.EXAM_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getExamType() {
        return examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.EXAM_TYPE
     *
     * @param examType the value for e_exam.EXAM_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setExamType(Integer examType) {
        this.examType = examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.B_TOPIC_NUM
     *
     * @return the value of e_exam.B_TOPIC_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getbTopicNum() {
        return bTopicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.B_TOPIC_NUM
     *
     * @param bTopicNum the value for e_exam.B_TOPIC_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setbTopicNum(Integer bTopicNum) {
        this.bTopicNum = bTopicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.M_TOPIC_NUM
     *
     * @return the value of e_exam.M_TOPIC_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getmTopicNum() {
        return mTopicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.M_TOPIC_NUM
     *
     * @param mTopicNum the value for e_exam.M_TOPIC_NUM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setmTopicNum(Integer mTopicNum) {
        this.mTopicNum = mTopicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.TOTAL
     *
     * @return the value of e_exam.TOTAL
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.TOTAL
     *
     * @param total the value for e_exam.TOTAL
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.CAREAOR
     *
     * @return the value of e_exam.CAREAOR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getCareaor() {
        return careaor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.CAREAOR
     *
     * @param careaor the value for e_exam.CAREAOR
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setCareaor(String careaor) {
        this.careaor = careaor == null ? null : careaor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.COST_TIME
     *
     * @return the value of e_exam.COST_TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getCostTime() {
        return costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.COST_TIME
     *
     * @param costTime the value for e_exam.COST_TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setCostTime(Integer costTime) {
        this.costTime = costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.REMARK
     *
     * @return the value of e_exam.REMARK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.REMARK
     *
     * @param remark the value for e_exam.REMARK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.Q_RANDOM
     *
     * @return the value of e_exam.Q_RANDOM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getqRandom() {
        return qRandom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.Q_RANDOM
     *
     * @param qRandom the value for e_exam.Q_RANDOM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setqRandom(Integer qRandom) {
        this.qRandom = qRandom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.O_RANDOM
     *
     * @return the value of e_exam.O_RANDOM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getoRandom() {
        return oRandom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.O_RANDOM
     *
     * @param oRandom the value for e_exam.O_RANDOM
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setoRandom(Integer oRandom) {
        this.oRandom = oRandom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.B_CODE_TYPE
     *
     * @return the value of e_exam.B_CODE_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getbCodeType() {
        return bCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.B_CODE_TYPE
     *
     * @param bCodeType the value for e_exam.B_CODE_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setbCodeType(Integer bCodeType) {
        this.bCodeType = bCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.S_CODE_TYPE
     *
     * @return the value of e_exam.S_CODE_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getsCodeType() {
        return sCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.S_CODE_TYPE
     *
     * @param sCodeType the value for e_exam.S_CODE_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setsCodeType(Integer sCodeType) {
        this.sCodeType = sCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.O_CODE_TYPE
     *
     * @return the value of e_exam.O_CODE_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getoCodeType() {
        return oCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.O_CODE_TYPE
     *
     * @param oCodeType the value for e_exam.O_CODE_TYPE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setoCodeType(Integer oCodeType) {
        this.oCodeType = oCodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.PASS_SCORE
     *
     * @return the value of e_exam.PASS_SCORE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Double getPassScore() {
        return passScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.PASS_SCORE
     *
     * @param passScore the value for e_exam.PASS_SCORE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setPassScore(Double passScore) {
        this.passScore = passScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.EXAM_AREA
     *
     * @return the value of e_exam.EXAM_AREA
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getExamArea() {
        return examArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.EXAM_AREA
     *
     * @param examArea the value for e_exam.EXAM_AREA
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setExamArea(Integer examArea) {
        this.examArea = examArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.TEST_ID
     *
     * @return the value of e_exam.TEST_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.TEST_ID
     *
     * @param testId the value for e_exam.TEST_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.RELEASE_STATUS
     *
     * @return the value of e_exam.RELEASE_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getReleaseStatus() {
        return releaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.RELEASE_STATUS
     *
     * @param releaseStatus the value for e_exam.RELEASE_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setReleaseStatus(Integer releaseStatus) {
        this.releaseStatus = releaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.RELEASE_TIME
     *
     * @return the value of e_exam.RELEASE_TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.RELEASE_TIME
     *
     * @param releaseTime the value for e_exam.RELEASE_TIME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.E_STATUS
     *
     * @return the value of e_exam.E_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer geteStatus() {
        return eStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.E_STATUS
     *
     * @param eStatus the value for e_exam.E_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void seteStatus(Integer eStatus) {
        this.eStatus = eStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_exam.GRADE_LEVEL
     *
     * @return the value of e_exam.GRADE_LEVEL
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getGradeLevel() {
        return gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_exam.GRADE_LEVEL
     *
     * @param gradeLevel the value for e_exam.GRADE_LEVEL
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setGradeLevel(Integer gradeLevel) {
        this.gradeLevel = gradeLevel;
    }
}