package com.eps.mybatis.auto.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HomeworkRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    protected Integer limitSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public HomeworkRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setLimitSize(Integer limitSize) {
        this.limitSize=limitSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getLimitSize() {
        return limitSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHwRecIdIsNull() {
            addCriterion("HW_REC_ID is null");
            return (Criteria) this;
        }

        public Criteria andHwRecIdIsNotNull() {
            addCriterion("HW_REC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHwRecIdEqualTo(Integer value) {
            addCriterion("HW_REC_ID =", value, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andHwRecIdNotEqualTo(Integer value) {
            addCriterion("HW_REC_ID <>", value, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andHwRecIdGreaterThan(Integer value) {
            addCriterion("HW_REC_ID >", value, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andHwRecIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("HW_REC_ID >=", value, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andHwRecIdLessThan(Integer value) {
            addCriterion("HW_REC_ID <", value, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andHwRecIdLessThanOrEqualTo(Integer value) {
            addCriterion("HW_REC_ID <=", value, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andHwRecIdIn(List<Integer> values) {
            addCriterion("HW_REC_ID in", values, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andHwRecIdNotIn(List<Integer> values) {
            addCriterion("HW_REC_ID not in", values, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andHwRecIdBetween(Integer value1, Integer value2) {
            addCriterion("HW_REC_ID between", value1, value2, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andHwRecIdNotBetween(Integer value1, Integer value2) {
            addCriterion("HW_REC_ID not between", value1, value2, "hwRecId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNull() {
            addCriterion("SUBJECT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNotNull() {
            addCriterion("SUBJECT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdEqualTo(Integer value) {
            addCriterion("SUBJECT_ID =", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotEqualTo(Integer value) {
            addCriterion("SUBJECT_ID <>", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThan(Integer value) {
            addCriterion("SUBJECT_ID >", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SUBJECT_ID >=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThan(Integer value) {
            addCriterion("SUBJECT_ID <", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("SUBJECT_ID <=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIn(List<Integer> values) {
            addCriterion("SUBJECT_ID in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotIn(List<Integer> values) {
            addCriterion("SUBJECT_ID not in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdBetween(Integer value1, Integer value2) {
            addCriterion("SUBJECT_ID between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SUBJECT_ID not between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andHwIdIsNull() {
            addCriterion("HW_ID is null");
            return (Criteria) this;
        }

        public Criteria andHwIdIsNotNull() {
            addCriterion("HW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHwIdEqualTo(Integer value) {
            addCriterion("HW_ID =", value, "hwId");
            return (Criteria) this;
        }

        public Criteria andHwIdNotEqualTo(Integer value) {
            addCriterion("HW_ID <>", value, "hwId");
            return (Criteria) this;
        }

        public Criteria andHwIdGreaterThan(Integer value) {
            addCriterion("HW_ID >", value, "hwId");
            return (Criteria) this;
        }

        public Criteria andHwIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("HW_ID >=", value, "hwId");
            return (Criteria) this;
        }

        public Criteria andHwIdLessThan(Integer value) {
            addCriterion("HW_ID <", value, "hwId");
            return (Criteria) this;
        }

        public Criteria andHwIdLessThanOrEqualTo(Integer value) {
            addCriterion("HW_ID <=", value, "hwId");
            return (Criteria) this;
        }

        public Criteria andHwIdIn(List<Integer> values) {
            addCriterion("HW_ID in", values, "hwId");
            return (Criteria) this;
        }

        public Criteria andHwIdNotIn(List<Integer> values) {
            addCriterion("HW_ID not in", values, "hwId");
            return (Criteria) this;
        }

        public Criteria andHwIdBetween(Integer value1, Integer value2) {
            addCriterion("HW_ID between", value1, value2, "hwId");
            return (Criteria) this;
        }

        public Criteria andHwIdNotBetween(Integer value1, Integer value2) {
            addCriterion("HW_ID not between", value1, value2, "hwId");
            return (Criteria) this;
        }

        public Criteria andFinishedNumIsNull() {
            addCriterion("FINISHED_NUM is null");
            return (Criteria) this;
        }

        public Criteria andFinishedNumIsNotNull() {
            addCriterion("FINISHED_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andFinishedNumEqualTo(Integer value) {
            addCriterion("FINISHED_NUM =", value, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andFinishedNumNotEqualTo(Integer value) {
            addCriterion("FINISHED_NUM <>", value, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andFinishedNumGreaterThan(Integer value) {
            addCriterion("FINISHED_NUM >", value, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andFinishedNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("FINISHED_NUM >=", value, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andFinishedNumLessThan(Integer value) {
            addCriterion("FINISHED_NUM <", value, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andFinishedNumLessThanOrEqualTo(Integer value) {
            addCriterion("FINISHED_NUM <=", value, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andFinishedNumIn(List<Integer> values) {
            addCriterion("FINISHED_NUM in", values, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andFinishedNumNotIn(List<Integer> values) {
            addCriterion("FINISHED_NUM not in", values, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andFinishedNumBetween(Integer value1, Integer value2) {
            addCriterion("FINISHED_NUM between", value1, value2, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andFinishedNumNotBetween(Integer value1, Integer value2) {
            addCriterion("FINISHED_NUM not between", value1, value2, "finishedNum");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagIsNull() {
            addCriterion("CORRECT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagIsNotNull() {
            addCriterion("CORRECT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagEqualTo(Integer value) {
            addCriterion("CORRECT_FLAG =", value, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagNotEqualTo(Integer value) {
            addCriterion("CORRECT_FLAG <>", value, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagGreaterThan(Integer value) {
            addCriterion("CORRECT_FLAG >", value, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("CORRECT_FLAG >=", value, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagLessThan(Integer value) {
            addCriterion("CORRECT_FLAG <", value, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagLessThanOrEqualTo(Integer value) {
            addCriterion("CORRECT_FLAG <=", value, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagIn(List<Integer> values) {
            addCriterion("CORRECT_FLAG in", values, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagNotIn(List<Integer> values) {
            addCriterion("CORRECT_FLAG not in", values, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagBetween(Integer value1, Integer value2) {
            addCriterion("CORRECT_FLAG between", value1, value2, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCorrectFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("CORRECT_FLAG not between", value1, value2, "correctFlag");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Integer value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Integer value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Integer value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Integer value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Integer> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Integer> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Integer value1, Integer value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCommitFlagIsNull() {
            addCriterion("COMMIT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andCommitFlagIsNotNull() {
            addCriterion("COMMIT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andCommitFlagEqualTo(Integer value) {
            addCriterion("COMMIT_FLAG =", value, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitFlagNotEqualTo(Integer value) {
            addCriterion("COMMIT_FLAG <>", value, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitFlagGreaterThan(Integer value) {
            addCriterion("COMMIT_FLAG >", value, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMMIT_FLAG >=", value, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitFlagLessThan(Integer value) {
            addCriterion("COMMIT_FLAG <", value, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitFlagLessThanOrEqualTo(Integer value) {
            addCriterion("COMMIT_FLAG <=", value, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitFlagIn(List<Integer> values) {
            addCriterion("COMMIT_FLAG in", values, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitFlagNotIn(List<Integer> values) {
            addCriterion("COMMIT_FLAG not in", values, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitFlagBetween(Integer value1, Integer value2) {
            addCriterion("COMMIT_FLAG between", value1, value2, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("COMMIT_FLAG not between", value1, value2, "commitFlag");
            return (Criteria) this;
        }

        public Criteria andCommitTimeIsNull() {
            addCriterion("COMMIT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCommitTimeIsNotNull() {
            addCriterion("COMMIT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCommitTimeEqualTo(Date value) {
            addCriterion("COMMIT_TIME =", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeNotEqualTo(Date value) {
            addCriterion("COMMIT_TIME <>", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeGreaterThan(Date value) {
            addCriterion("COMMIT_TIME >", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("COMMIT_TIME >=", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeLessThan(Date value) {
            addCriterion("COMMIT_TIME <", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeLessThanOrEqualTo(Date value) {
            addCriterion("COMMIT_TIME <=", value, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeIn(List<Date> values) {
            addCriterion("COMMIT_TIME in", values, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeNotIn(List<Date> values) {
            addCriterion("COMMIT_TIME not in", values, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeBetween(Date value1, Date value2) {
            addCriterion("COMMIT_TIME between", value1, value2, "commitTime");
            return (Criteria) this;
        }

        public Criteria andCommitTimeNotBetween(Date value1, Date value2) {
            addCriterion("COMMIT_TIME not between", value1, value2, "commitTime");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("SCORE is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Double value) {
            addCriterion("SCORE =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Double value) {
            addCriterion("SCORE <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Double value) {
            addCriterion("SCORE >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Double value) {
            addCriterion("SCORE >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Double value) {
            addCriterion("SCORE <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Double value) {
            addCriterion("SCORE <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Double> values) {
            addCriterion("SCORE in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Double> values) {
            addCriterion("SCORE not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Double value1, Double value2) {
            addCriterion("SCORE between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Double value1, Double value2) {
            addCriterion("SCORE not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("STUDENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("STUDENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("STUDENT_ID =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("STUDENT_ID <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("STUDENT_ID >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("STUDENT_ID >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("STUDENT_ID <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("STUDENT_ID <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("STUDENT_ID in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("STUDENT_ID not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("STUDENT_ID between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("STUDENT_ID not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNull() {
            addCriterion("CLASS_ID is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("CLASS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Integer value) {
            addCriterion("CLASS_ID =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Integer value) {
            addCriterion("CLASS_ID <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Integer value) {
            addCriterion("CLASS_ID >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CLASS_ID >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Integer value) {
            addCriterion("CLASS_ID <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("CLASS_ID <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Integer> values) {
            addCriterion("CLASS_ID in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Integer> values) {
            addCriterion("CLASS_ID not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Integer value1, Integer value2) {
            addCriterion("CLASS_ID between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CLASS_ID not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andStarIsNull() {
            addCriterion("STAR is null");
            return (Criteria) this;
        }

        public Criteria andStarIsNotNull() {
            addCriterion("STAR is not null");
            return (Criteria) this;
        }

        public Criteria andStarEqualTo(Integer value) {
            addCriterion("STAR =", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotEqualTo(Integer value) {
            addCriterion("STAR <>", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarGreaterThan(Integer value) {
            addCriterion("STAR >", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarGreaterThanOrEqualTo(Integer value) {
            addCriterion("STAR >=", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarLessThan(Integer value) {
            addCriterion("STAR <", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarLessThanOrEqualTo(Integer value) {
            addCriterion("STAR <=", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarIn(List<Integer> values) {
            addCriterion("STAR in", values, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotIn(List<Integer> values) {
            addCriterion("STAR not in", values, "star");
            return (Criteria) this;
        }

        public Criteria andStarBetween(Integer value1, Integer value2) {
            addCriterion("STAR between", value1, value2, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotBetween(Integer value1, Integer value2) {
            addCriterion("STAR not between", value1, value2, "star");
            return (Criteria) this;
        }

        public Criteria andCommentRecIsNull() {
            addCriterion("COMMENT_REC is null");
            return (Criteria) this;
        }

        public Criteria andCommentRecIsNotNull() {
            addCriterion("COMMENT_REC is not null");
            return (Criteria) this;
        }

        public Criteria andCommentRecEqualTo(String value) {
            addCriterion("COMMENT_REC =", value, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecNotEqualTo(String value) {
            addCriterion("COMMENT_REC <>", value, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecGreaterThan(String value) {
            addCriterion("COMMENT_REC >", value, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENT_REC >=", value, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecLessThan(String value) {
            addCriterion("COMMENT_REC <", value, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecLessThanOrEqualTo(String value) {
            addCriterion("COMMENT_REC <=", value, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecLike(String value) {
            addCriterion("COMMENT_REC like", value, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecNotLike(String value) {
            addCriterion("COMMENT_REC not like", value, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecIn(List<String> values) {
            addCriterion("COMMENT_REC in", values, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecNotIn(List<String> values) {
            addCriterion("COMMENT_REC not in", values, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecBetween(String value1, String value2) {
            addCriterion("COMMENT_REC between", value1, value2, "commentRec");
            return (Criteria) this;
        }

        public Criteria andCommentRecNotBetween(String value1, String value2) {
            addCriterion("COMMENT_REC not between", value1, value2, "commentRec");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_hw_record
     *
     * @mbggenerated do_not_delete_during_merge Tue May 26 14:51:53 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_hw_record
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}