package com.eps.mybatis.auto.entity;

import java.util.Date;

public class Link extends LinkKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_link.CREATE_DATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_link.LINK_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer linkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_link.USE_DATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Date useDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_link.CREATE_DATE
     *
     * @return the value of s_link.CREATE_DATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_link.CREATE_DATE
     *
     * @param createDate the value for s_link.CREATE_DATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_link.LINK_STATUS
     *
     * @return the value of s_link.LINK_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getLinkStatus() {
        return linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_link.LINK_STATUS
     *
     * @param linkStatus the value for s_link.LINK_STATUS
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setLinkStatus(Integer linkStatus) {
        this.linkStatus = linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_link.USE_DATE
     *
     * @return the value of s_link.USE_DATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Date getUseDate() {
        return useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_link.USE_DATE
     *
     * @param useDate the value for s_link.USE_DATE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setUseDate(Date useDate) {
        this.useDate = useDate;
    }
}