package com.eps.mybatis.auto.entity;

public class Parameter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_parameter.PARAMETER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer parameterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_parameter.PARAMETER_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String parameterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_parameter.PARAMETER_VALUE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String parameterValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_parameter.ORG_NO
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String orgNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_parameter.REMARK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_parameter.PARAMETER_ID
     *
     * @return the value of s_parameter.PARAMETER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getParameterId() {
        return parameterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_parameter.PARAMETER_ID
     *
     * @param parameterId the value for s_parameter.PARAMETER_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setParameterId(Integer parameterId) {
        this.parameterId = parameterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_parameter.PARAMETER_NAME
     *
     * @return the value of s_parameter.PARAMETER_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_parameter.PARAMETER_NAME
     *
     * @param parameterName the value for s_parameter.PARAMETER_NAME
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName == null ? null : parameterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_parameter.PARAMETER_VALUE
     *
     * @return the value of s_parameter.PARAMETER_VALUE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getParameterValue() {
        return parameterValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_parameter.PARAMETER_VALUE
     *
     * @param parameterValue the value for s_parameter.PARAMETER_VALUE
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setParameterValue(String parameterValue) {
        this.parameterValue = parameterValue == null ? null : parameterValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_parameter.ORG_NO
     *
     * @return the value of s_parameter.ORG_NO
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_parameter.ORG_NO
     *
     * @param orgNo the value for s_parameter.ORG_NO
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo == null ? null : orgNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_parameter.REMARK
     *
     * @return the value of s_parameter.REMARK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_parameter.REMARK
     *
     * @param remark the value for s_parameter.REMARK
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}