package com.eps.mybatis.auto.entity;

public class SeatKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_seat.SEAT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer seatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_seat.CLASS_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_seat.STUDENT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_seat.SEAT_ID
     *
     * @return the value of c_seat.SEAT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_seat.SEAT_ID
     *
     * @param seatId the value for c_seat.SEAT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_seat.CLASS_ID
     *
     * @return the value of c_seat.CLASS_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_seat.CLASS_ID
     *
     * @param classId the value for c_seat.CLASS_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_seat.STUDENT_ID
     *
     * @return the value of c_seat.STUDENT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_seat.STUDENT_ID
     *
     * @param studentId the value for c_seat.STUDENT_ID
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}