package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.AnalyPerson;
import com.eps.mybatis.auto.entity.AnalyPersonExample;
import com.eps.mybatis.auto.entity.AnalyPersonKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnalyPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(AnalyPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(AnalyPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(AnalyPersonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(AnalyPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(AnalyPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<AnalyPerson> selectByExample(AnalyPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    AnalyPerson selectByPrimaryKey(AnalyPersonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") AnalyPerson record, @Param("example") AnalyPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") AnalyPerson record, @Param("example") AnalyPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(AnalyPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_analy_person
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(AnalyPerson record);
}