package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.Catalog;
import com.eps.mybatis.auto.entity.CatalogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(Integer caId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<Catalog> selectByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    Catalog selectByPrimaryKey(Integer caId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") Catalog record, @Param("example") CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") Catalog record, @Param("example") CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(Catalog record);
}