package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.CatalogRel;
import com.eps.mybatis.auto.entity.CatalogRelExample;
import com.eps.mybatis.auto.entity.CatalogRelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CatalogRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(CatalogRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(CatalogRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(CatalogRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(CatalogRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(CatalogRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<CatalogRel> selectByExample(CatalogRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    CatalogRel selectByPrimaryKey(CatalogRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") CatalogRel record, @Param("example") CatalogRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") CatalogRel record, @Param("example") CatalogRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(CatalogRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_catalog_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(CatalogRel record);
}