package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.ClassStudent;
import com.eps.mybatis.auto.entity.ClassStudentExample;
import com.eps.mybatis.auto.entity.ClassStudentKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(ClassStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(ClassStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(ClassStudentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(ClassStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(ClassStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<ClassStudent> selectByExampleWithBLOBs(ClassStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<ClassStudent> selectByExample(ClassStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    ClassStudent selectByPrimaryKey(ClassStudentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") ClassStudent record, @Param("example") ClassStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") ClassStudent record, @Param("example") ClassStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") ClassStudent record, @Param("example") ClassStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(ClassStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ClassStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_class_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(ClassStudent record);
}