package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.ExamPreview;
import com.eps.mybatis.auto.entity.ExamPreviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamPreviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(ExamPreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(ExamPreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(Integer examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(ExamPreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(ExamPreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<ExamPreview> selectByExample(ExamPreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    ExamPreview selectByPrimaryKey(Integer examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") ExamPreview record, @Param("example") ExamPreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") ExamPreview record, @Param("example") ExamPreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(ExamPreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_preview
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(ExamPreview record);
}