package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.ExamQuestion;
import com.eps.mybatis.auto.entity.ExamQuestionExample;
import com.eps.mybatis.auto.entity.ExamQuestionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(ExamQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(ExamQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(ExamQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(ExamQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(ExamQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<ExamQuestion> selectByExample(ExamQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    ExamQuestion selectByPrimaryKey(ExamQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") ExamQuestion record, @Param("example") ExamQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") ExamQuestion record, @Param("example") ExamQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(ExamQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_exam_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(ExamQuestion record);
}