package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.HomeworkRecordDetail;
import com.eps.mybatis.auto.entity.HomeworkRecordDetailExample;
import com.eps.mybatis.auto.entity.HomeworkRecordDetailKey;
import com.eps.mybatis.auto.entity.HomeworkRecordDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeworkRecordDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(HomeworkRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(HomeworkRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(HomeworkRecordDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(HomeworkRecordDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(HomeworkRecordDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<HomeworkRecordDetailWithBLOBs> selectByExampleWithBLOBs(HomeworkRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<HomeworkRecordDetail> selectByExample(HomeworkRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    HomeworkRecordDetailWithBLOBs selectByPrimaryKey(HomeworkRecordDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") HomeworkRecordDetailWithBLOBs record, @Param("example") HomeworkRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") HomeworkRecordDetailWithBLOBs record, @Param("example") HomeworkRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") HomeworkRecordDetail record, @Param("example") HomeworkRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(HomeworkRecordDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(HomeworkRecordDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(HomeworkRecordDetail record);
}