package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.HomeworkQuestion;
import com.eps.mybatis.auto.entity.HomeworkQuestionExample;
import com.eps.mybatis.auto.entity.HomeworkQuestionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeworkQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(HomeworkQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(HomeworkQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(HomeworkQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<HomeworkQuestion> selectByExample(HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    HomeworkQuestion selectByPrimaryKey(HomeworkQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") HomeworkQuestion record, @Param("example") HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") HomeworkQuestion record, @Param("example") HomeworkQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(HomeworkQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_hw_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(HomeworkQuestion record);
}