package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.KnowledgeRel;
import com.eps.mybatis.auto.entity.KnowledgeRelExample;
import com.eps.mybatis.auto.entity.KnowledgeRelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KnowledgeRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(KnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(KnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(KnowledgeRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(KnowledgeRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(KnowledgeRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<KnowledgeRel> selectByExample(KnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    KnowledgeRel selectByPrimaryKey(KnowledgeRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") KnowledgeRel record, @Param("example") KnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") KnowledgeRel record, @Param("example") KnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(KnowledgeRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_kp_rel
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(KnowledgeRel record);
}