package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.Option;
import com.eps.mybatis.auto.entity.OptionExample;
import com.eps.mybatis.auto.entity.OptionWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(Integer optId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(OptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(OptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<OptionWithBLOBs> selectByExampleWithBLOBs(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<Option> selectByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    OptionWithBLOBs selectByPrimaryKey(Integer optId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") OptionWithBLOBs record, @Param("example") OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") OptionWithBLOBs record, @Param("example") OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") Option record, @Param("example") OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(OptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(OptionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_option
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(Option record);
}