package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.Question;
import com.eps.mybatis.auto.entity.QuestionExample;
import com.eps.mybatis.auto.entity.QuestionWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(Integer quesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(QuestionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(QuestionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<QuestionWithBLOBs> selectByExampleWithBLOBs(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<Question> selectByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    QuestionWithBLOBs selectByPrimaryKey(Integer quesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") QuestionWithBLOBs record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") QuestionWithBLOBs record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(QuestionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(QuestionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_question
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(Question record);
}