package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.Student;
import com.eps.mybatis.auto.entity.StudentExample;
import com.eps.mybatis.auto.entity.StudentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<StudentWithBLOBs> selectByExampleWithBLOBs(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    StudentWithBLOBs selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") StudentWithBLOBs record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") StudentWithBLOBs record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(StudentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_student
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(Student record);
}