package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.TestExam;
import com.eps.mybatis.auto.entity.TestExamExample;
import com.eps.mybatis.auto.entity.TestExamKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(TestExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(TestExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(TestExamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(TestExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(TestExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<TestExam> selectByExample(TestExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    TestExam selectByPrimaryKey(TestExamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") TestExam record, @Param("example") TestExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") TestExam record, @Param("example") TestExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(TestExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_exam
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(TestExam record);
}