package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.TestRecordDetail;
import com.eps.mybatis.auto.entity.TestRecordDetailExample;
import com.eps.mybatis.auto.entity.TestRecordDetailKey;
import com.eps.mybatis.auto.entity.TestRecordDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestRecordDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(TestRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(TestRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(TestRecordDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(TestRecordDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(TestRecordDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<TestRecordDetailWithBLOBs> selectByExampleWithBLOBs(TestRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<TestRecordDetail> selectByExample(TestRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    TestRecordDetailWithBLOBs selectByPrimaryKey(TestRecordDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") TestRecordDetailWithBLOBs record, @Param("example") TestRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") TestRecordDetailWithBLOBs record, @Param("example") TestRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") TestRecordDetail record, @Param("example") TestRecordDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(TestRecordDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(TestRecordDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_test_record_detail
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(TestRecordDetail record);
}