package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.TypeSubject;
import com.eps.mybatis.auto.entity.TypeSubjectExample;
import com.eps.mybatis.auto.entity.TypeSubjectKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TypeSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(TypeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(TypeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(TypeSubjectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(TypeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(TypeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<TypeSubject> selectByExample(TypeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    TypeSubject selectByPrimaryKey(TypeSubjectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") TypeSubject record, @Param("example") TypeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") TypeSubject record, @Param("example") TypeSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(TypeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_type_subject
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(TypeSubject record);
}