package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.Warranty;
import com.eps.mybatis.auto.entity.WarrantyExample;
import com.eps.mybatis.auto.entity.WarrantyKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WarrantyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(WarrantyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(WarrantyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(WarrantyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(Warranty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(Warranty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<Warranty> selectByExample(WarrantyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    Warranty selectByPrimaryKey(WarrantyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") Warranty record, @Param("example") WarrantyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") Warranty record, @Param("example") WarrantyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(Warranty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_warranty
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(Warranty record);
}