package com.eps.mybatis.auto;

import com.eps.mybatis.auto.entity.ZhujuanQues;
import com.eps.mybatis.auto.entity.ZhujuanQuesExample;
import com.eps.mybatis.auto.entity.ZhujuanQuesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhujuanQuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int countByExample(ZhujuanQuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByExample(ZhujuanQuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insert(ZhujuanQuesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int insertSelective(ZhujuanQuesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<ZhujuanQuesWithBLOBs> selectByExampleWithBLOBs(ZhujuanQuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    List<ZhujuanQues> selectByExample(ZhujuanQuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    ZhujuanQuesWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") ZhujuanQuesWithBLOBs record, @Param("example") ZhujuanQuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") ZhujuanQuesWithBLOBs record, @Param("example") ZhujuanQuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByExample(@Param("record") ZhujuanQues record, @Param("example") ZhujuanQuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeySelective(ZhujuanQuesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ZhujuanQuesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_ques
     *
     * @mbggenerated Tue May 26 14:51:53 CST 2015
     */
    int updateByPrimaryKey(ZhujuanQues record);
}